services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Puerto para comunicaci칩n con RabbitMQ
      - "15672:15672" # UI de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  emitlogtopic:
    build:
      context: ./EmitLogTopic
    container_name: emitlogtopic
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      ABBITMQ_USER: user  # Usuario de RabbitMQ
      RABBITMQ_PASS: password  # Contrase침a de RabbitMQ

  emitcattopic:
    build:
      context: ./EmitCatTopic
    container_name: emitcattopic
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      ABBITMQ_USER: user  # Usuario de RabbitMQ
      RABBITMQ_PASS: password  # Contrase침a de RabbitMQ

  receivelogstopic:
    build:
      context: ./ReceiveLogsTopic
    container_name: receivelogstopic
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user  # Usuario de RabbitMQ
      RABBITMQ_PASS: password  # Contrase침a de RabbitMQ
